"""updated id to user_id

Revision ID: ce956f01ef48
Revises: f267a98ca4ba
Create Date: 2024-08-26 14:57:44.602750

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ce956f01ef48"
down_revision = "f267a98ca4ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("user_id", sa.UUID(), nullable=False))
    op.drop_column("users", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("id", sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column("users", "user_id")
    # ### end Alembic commands ###
